feat(zshrc): customize zsh history function to prevent from conserving failed history

diff --git a/dot_zshrc b/dot_zshrc
--- a/dot_zshrc
+++ b/dot_zshrc
@@ -31,3 +31,10 @@ if type mise > /dev/null 2>&1; then
 else
     echo "NOT found mise command. please install mise"
 fi
+
+### Custom functions ###
+# Prevent from conserving failed history
+# https://zsh.sourceforge.io/Doc/Release/Functions.html#Hook-Functions
+zshaddhistory() {
+    [[ "$?" == 0 ]]
+}
